# SPDX-FileCopyrightText: 2021 Serokell <https://serokell.io/>
#
# SPDX-License-Identifier: MPL-2.0

name: algorand-sdk
version: 0.0.0.1
synopsis: A Haskell SDK for the Algorand blockchain
description: |
  Tools for working with transactions on the Algorand blockchain
  and interacting with algod through its REST API.
category: Algorand, Finance, Blockchain

author: Kirill Elagin <kirelagin@serokell.io>
copyright: 2021 Serokell
license-file: LICENSES/MPL-2.0.txt

github: serokell/haskell-algorand

extra-source-files:
  - CHANGELOG.md
  - README.md

dependencies:
  - base >= 4.7 && < 4.15
  - bytestring >= 0.9 && < 0.11
  - memory >= 0.1 && < 0.16
  - safe-exceptions >= 0.1 && < 0.2
  - text >= 0.1 && < 1.3
  - fmt >= 0.6 && < 0.7

library:
  source-dirs: src

  dependencies:
    - aeson >= 1.3 && < 1.5
    - aeson-casing >= 0.1.1.0 && < 0.3
      # There is a bug in base32 < 0.2
    - base32 >= 0.2 && < 0.3
    - base64 >= 0.0.1.0 && < 0.5
    - containers >= 0.5 && < 0.7
    - cryptonite >= 0.1
    - data-default-class >= 0.1.2 && < 0.2
    - http-client-tls >= 0.3.4 && < 0.4
    - http-media >= 0.1 && < 0.9
    - msgpack-binary >= 0.0.14 && < 0.1
    - msgpack-types >= 0.0.4 && < 0.1
    - servant >= 0.14 && < 0.19
    - servant-client >= 0.14 && < 0.19
    - servant-client-core >= 0.14 && < 0.19
    - scientific >= 0.3.3 && < 0.3.7
    - time
    - unordered-containers >= 0.1.3 && < 0.3

executables:
  halgo:
    source-dirs: app/halgo
    main: Main.hs

    dependencies:
      - algorand-sdk

      - aeson
      - aeson-pretty >= 0.3 && < 0.9
      - base64
      - directory >= 1.2.7.0 && < 1.4
      - filepath >= 1.0 && < 1.5
      - http-types >= 0.1.1 && < 0.13
      - mtl >= 1.0 && < 2.3
      - optparse-applicative >= 0.15 && < 0.17 # the lower bound is not tight
      - servant-client
      - servant-client-core
      - text
      - unliftio >= 0.1 && < 0.3
      - with-utf8 >= 1.0 && < 1.1

tests:
  algorand-lib-test:
    source-dirs: test/algorand-lib
    main: Main.hs

    dependencies:
      - algorand-sdk

      - hedgehog
      - HUnit
      - tasty
      - tasty-hedgehog
      - tasty-hunit

      - aeson
      - base32
      - base64
      - msgpack-binary

    build-tools:
      - tasty-discover:tasty-discover

default-extensions:
  - AllowAmbiguousTypes
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveGeneric
  - DerivingStrategies
  - DuplicateRecordFields
  - EmptyCase
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - OverloadedLabels
  - PatternSynonyms
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeFamilies
  - TypeOperators
  - UndecidableInstances
  - ViewPatterns
  - TypeApplications

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
