# SPDX-FileCopyrightText: 2021 Serokell <https://serokell.io/>
#
# SPDX-License-Identifier: CC0-1.0

resolver: lts-18.12

packages:
  - .

extra-deps:
  # Not in the snapshot
  - msgpack-binary-0.0.14
  - msgpack-types-0.0.4

nix:
  packages: [zlib]
